[package]
name = "filetruck"
version = "0.1.0"
authors = ["Eamonn Laffey <eamonn.laffey@gmail.com>"]
edition = "2018"

[dependencies]
argh = "0.1.3"
serde = {version = "1.0.114", features = ["derive"]}
serde_yaml = "0.8.13"
same-file = "1.0.6"

